name: maturity_model
description: Information for Systems for Health (IS4H) Maturity Assessment.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  creator: ^0.3.3
  csv: ^6.0.0
  data_table_2: ^2.6.0
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  graphic: ^2.6.0
  gsheets: ^0.5.0

dev_dependencies:
  build_runner: ^2.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
