name: maturity_model
description: Information for Systems for Health (IS4H) Maturity Assessment.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  creator: ^0.2.0
  cupertino_icons: ^1.0.5
  gap: ^2.0.0
  gsheets: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets: 
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
