name: maturity_model
description: Information for Systems for Health (IS4H) Maturity Assessment.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  creator: ^0.2.0
  csv: ^5.0.1
  cupertino_icons: ^1.0.5
  data_table_2: ^2.3.6
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  graphic: ^0.10.6
  gsheets: ^0.4.2
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets: 
    - assets/
